name: CI

on: [push, pull_request]

jobs:
  linux:
    name: Linux (${{ matrix.backend }})
    runs-on: ubuntu-20.04 # for OpenSSL 1.1.1
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: openssl
          - backend: botan
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo apt update -qq
          sudo apt install libcppunit-dev libbotan-2-dev p11-kit
      - name: Build
        run: |
          ./autogen.sh
          ./configure --with-crypto-backend=${{ matrix.backend }}
          make
      - name: Test
        run: |
          make check || (find . -name test-suite.log -exec cat {} \; && false)

  macos:
    name: macOS (${{ matrix.backend }})
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: openssl
            extra-options: --with-openssl=$(brew --prefix openssl@1.1)
          - backend: botan
            extra-options: --with-botan=$(brew --prefix botan@2)
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          brew install automake cppunit botan@2
      - name: Build
        run: |
          ./autogen.sh
          ./configure --with-crypto-backend=${{ matrix.backend }} ${{ matrix.extra-options }}
          make
      - name: Test
        run: |
          make check || (find . -name test-suite.log -exec cat {} \; && false)

  windows:
    name: Windows (${{ matrix.arch }}, ${{ matrix.backend }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            backend: openssl
            target-platform: x64
          - arch: x64
            backend: botan
            target-platform: x64
          - arch: x86
            backend: openssl
            target-platform: Win32
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Create vcpkg.json
        run: >
          echo '{ "dependencies": [ "openssl", "botan", "cppunit" ],
                  "overrides": [ { "name": "openssl", "version-string": "1.1.1n" },
                                 { "name": "botan",   "version-string": "2.19.3" } ],
                  "builtin-baseline": "38d1652f152d36481f2f4e8a85c0f1e14f3769f7" }' > vcpkg.json
      - uses: seanmiddleditch/vcpkg-action@master
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: ${{ matrix.arch }}-windows
          token: ${{ github.token }}
      - name: Build
        run: |
          mkdir build
          cmake -B build ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -A ${{ matrix.target-platform }} -DWITH_CRYPTO_BACKEND=${{ matrix.backend }} -DDISABLE_NON_PAGED_MEMORY=ON -DBUILD_TESTS=ON
          cmake --build build
      - name: Test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cmake --build build --target RUN_TESTS
